apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main-gitops-app
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/davidcode2/app-of-apps
    targetRevision: HEAD
    path: . # ArgoCD will look for YAML files in the root of the repo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
