apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: its-time-for-smiles
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Davidcode2/app-of-apps
    path: its-time-for-smiles
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: smiles
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
