apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: schluesselmomente-cms
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/davidcode2/app-of-apps
    targetRevision: HEAD
    path: schluesselmomente-cms
  destination:
    server: https://kubernetes.default.svc
    namespace: schluesselmomente-cms
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
