#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: traefik
#  namespace: argocd
#  finalizers:
#    - resources-finalizer.argocd.argoproj.io
#spec:
#  project: default
#  destination:
#    namespace: traefik
#    server: https://kubernetes.default.svc
#  source:
#    repoURL: https://github.com/davidcode2/app-of-apps
#    targetRevision: HEAD
#    path: traefik
#    helm:
#      valueFiles:
#        - values.yaml
#  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
#    syncOptions:
#      - CreateNamespace=true
