apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vacation
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/davidcode2/app-of-apps
    targetRevision: HEAD
    path: vacation
  destination:
    server: https://kubernetes.default.svc
    namespace: vacation
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
