apiVersion: v1
kind: Secret
metadata:
  name: immoly-db-secret
  namespace: immoly
type: Opaque
data:
  # base64 encoded
  POSTGRES_PASSWORD: c245YkJrR3hiNUdGWmFxejg1VFNvdm9URw==
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_CONNECTION_STRING: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnNuOWJCa0d4YjVHRlphcXo4NVRTb3ZvVEdAaW1tb2x5LXBvc3RncmVzOjU0MzIvcG9zdGdyZXM=

