apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-db
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: ghcr.io/davidcode2/immoly-migrations:latest
          command: ["drizzle-kit", "migrate"]
        - env:
            - name: PGDATA
              value: /var/lib/postgresql/data
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immoly-db-secret
                  key: DB_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: immoly-db-secret
                  key: DB_USER
            - name: POSTGRES_CONNECTION_STRING
              valueFrom: 
                secretKeyRef:
                  name: immoly-db-secret
                  key: POSTGRES_CONNECTION_STRING 
