apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: immoly-volume
  name: immoly-volume
  namespace: immoly
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
