apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app: immoly-postgres
  name: immoly-postgres
  namespace: immoly
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: immoly-postgres
      app: immoly-postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: immoly-postgres
        app: immoly-postgres
    spec:
      containers:
        - image: postgres:16.0-alpine
          name: immoly-postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: immoly-volume
          envFrom:
            - configMapRef:
                name: env
            - secretRef:
                name: immoly-db-secret
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
                - -d
                - postgres
            failureThreshold: 5
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
      restartPolicy: Always
      volumes:
        - name: immoly-volume
          persistentVolumeClaim:
            claimName: immoly-volume
