apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: umami-db-data
  namespace: umami
  labels:
    app: umami-db
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
