apiVersion: apps/v1
kind: Deployment
metadata:
  name: umami-db
  namespace: umami
  labels:
    app: umami-db
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: umami-db
  template:
    metadata:
      labels:
        app: umami-db
    spec:
      containers:
        - image: postgres:16.0-alpine
          name: umami-db
          envFrom:
            - secretRef:
                name: umami-db-secret
          env:
            - name: POSTGRES_DB
              value: umami
            - name: POSTGRES_USER
              value: umami
            - name: PGDATA
              value: /var/lib/postgresql/data
          ports:
            - containerPort: 5432
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: umami-db-data
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - umami
                - -d
                - umami
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 5
      volumes:
        - name: umami-db-data
          persistentVolumeClaim:
            claimName: umami-db-data
      restartPolicy: Always
