apiVersion: v2
name: gmymf-medusa
description: A Helm chart for GMWMF Medusa Backend
type: application
version: 0.1.0
appVersion: "0.0.1"
dependencies:
  - name: medusa-backend
    version: 0.1.0
    repository: file://../../medusa-backend/k8s/helm
