apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gmymf-medusa-secrets
  namespace: gmymf-medusa
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 6h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: gmymf-medusa-secrets
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: /gmymf-medusa/jwt/secret
    - secretKey: COOKIE_SECRET
      remoteRef:
        key: /gmymf-medusa/cookie/secret
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: /gmymf-medusa/db/password
