apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gmymf-medusa-postgres
  namespace: gmymf-medusa
  labels:
    app: postgres
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
