apiVersion: v2
name: traefik
description: Traefik Ingress Controller with NGINX annotation compatibility
type: application
version: 1.0.0
dependencies:
  - name: traefik
    version: "40.0.0-ea.3"
    repository: https://traefik.github.io/charts
