apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-repo-creds-gitops
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: argocd-repo-creds-gitops
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: Opaque
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
      data:
        url: "https://github.com/davidcode2/"
        githubAppID: "4611437"
        githubAppInstallationID: "154107422"
        githubAppPrivateKey: "{{ .privateKey }}"
  data:
    - secretKey: privateKey
      remoteRef:
        key: /argocd/github-app-private-key
