apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gmymf-medusa-secrets
  namespace: gmymf-medusa
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 6h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: gmymf-medusa-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        JWT_SECRET: "{{ .jwt_secret }}"
        COOKIE_SECRET: "{{ .cookie_secret }}"
        POSTGRES_PASSWORD: "{{ .postgres_password }}"
        DATABASE_URL: "postgres://postgres:{{ .postgres_password }}@gmymf-medusa-postgres:5432/medusa_store"
  data:
    - secretKey: jwt_secret
      remoteRef:
        key: /gmymf-medusa/jwt/secret
    - secretKey: cookie_secret
      remoteRef:
        key: /gmymf-medusa/cookie/secret
    - secretKey: postgres_password
      remoteRef:
        key: /gmymf-medusa/db/password
