apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gmymf-storefront-medusa-secret
  namespace: gmymf-storefront
spec:
  refreshInterval: 6h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: gmymf-storefront-medusa-secret
    creationPolicy: Owner
  data:
    - secretKey: publishable_key
      remoteRef:
        key: /gmymf-storefront/medusa/publishable_key
