apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: home-at-sea-strapi-external-secret
  namespace: home-at-sea
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore

  target:
    name: home-at-sea-strapi-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # Strapi secrets
        ADMIN_JWT_SECRET: "{{ .admin_jwt_secret }}"
        API_TOKEN_SALT: "{{ .api_token_salt }}"
        APP_KEYS: "{{ .app_keys }}"
        JWT_SECRET: "{{ .jwt_secret }}"
        TRANSFER_TOKEN_SALT: "{{ .transfer_token_salt }}"
        ENCRYPTION_KEY: "{{ .encryption_key }}"
        # Database config
        DATABASE_CLIENT: postgres
        DATABASE_HOST: home-at-sea-postgres-service
        DATABASE_PORT: "5432"
        DATABASE_NAME: strapi
        DATABASE_USERNAME: strapi_user
        DATABASE_PASSWORD: "{{ .database_password }}"
        # Postgres container env vars
        POSTGRES_DB: strapi
        POSTGRES_USER: strapi_user
        POSTGRES_PASSWORD: "{{ .database_password }}"

  data:
    - secretKey: admin_jwt_secret
      remoteRef:
        key: /home_at_sea/strapi/admin_jwt_secret
    - secretKey: api_token_salt
      remoteRef:
        key: /home_at_sea/strapi/api_token_salt
    - secretKey: app_keys
      remoteRef:
        key: /home_at_sea/strapi/app_keys
    - secretKey: jwt_secret
      remoteRef:
        key: /home_at_sea/strapi/jwt_secret
    - secretKey: transfer_token_salt
      remoteRef:
        key: /home_at_sea/strapi/transfer_token_salt
    - secretKey: encryption_key
      remoteRef:
        key: /home_at_sea/strapi/encryption_key
    - secretKey: database_password
      remoteRef:
        key: /home_at_sea/strapi/db/password
