apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immoly-db-external-secret
  namespace: immoly
spec:
  refreshInterval: 6h
  
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  
  target:
    name: immoly-db-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # The values will be base64 encoded automatically
        POSTGRES_PASSWORD: "{{ .postgres_password }}"
        POSTGRES_USER: "{{ .postgres_user }}"
        POSTGRES_CONNECTION_STRING: "postgresql://{{ .postgres_user }}:{{ .postgres_password }}@immoly-postgres:5432/postgres"
  
  data:
    - secretKey: postgres_password
      remoteRef:
        key: /immoly/db/password  # AWS Parameter Store path
    - secretKey: postgres_user
      remoteRef:
        key: /immoly/db/user  # AWS Parameter Store path
