apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alemazung-strapi-app-external-secret
  namespace: joy-alemazung
spec:
  # Sync frequency - set to 6 hours
  refreshInterval: 2m
  
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  
  # Target secret that will be created/updated in Kubernetes
  target:
    name: alemazung-strapi-app-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # Map the AWS Parameter Store keys to Kubernetes secret keys
        # External Secrets will handle base64 encoding
        TRANSFER_TOKEN_SALT: "{{ .transfer_token_salt }}"
        JWT_SECRET: "{{ .jwt_secret }}"
        ENCRYPTION_KEY: "{{ .encryption_key }}"
        DATABASE_PASSWORD: "{{ .database_password }}"
        APP_KEYS: "{{ .app_keys }}"
        API_TOKEN_SALT: "{{ .api_token_salt }}"
        ADMIN_JWT_SECRET: "{{ .admin_jwt_secret }}"
        DATABASE_CLIENT: postgres
        DATABASE_FILENAME: ""
        DATABASE_HOST: strapi-postgres-service
        DATABASE_NAME: strapi
        DATABASE_PORT: "5432"
        DATABASE_SSL: "false"
        DATABASE_USERNAME: strapi_user
        HOST: 0.0.0.0
        NODE_ENV: development
        PORT: "1337"
        # PostgreSQL-specific environment variables
        POSTGRES_DB: strapi
        POSTGRES_USER: strapi_user
        POSTGRES_PASSWORD: "{{ .database_password }}"
  
  # Define which parameters to fetch from AWS Parameter Store
  data:
    - secretKey: admin_jwt_secret
      remoteRef:
        key: /joy_alemazung/strapi/admin_jwt_secret
    - secretKey: api_token_salt
      remoteRef:
        key: /joy_alemazung/strapi/api_token_salt
    - secretKey: app_keys
      remoteRef:
        key: /joy_alemazung/strapi/app_keys
    - secretKey: database_password
      remoteRef:
        key: /joy_alemazung/strapi/db/password
    - secretKey: encryption_key
      remoteRef:
        key: /joy_alemazung/strapi/db/encryption_key
    - secretKey: jwt_secret
      remoteRef:
        key: /joy_alemazung/strapi/jwt_secret
    - secretKey: transfer_token_salt
      remoteRef:
        key: /joy_alemazung/strapi/transfer_token_salt

