apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: message-router-sites-external-secret
  namespace: message-router
spec:
  refreshInterval: 6h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: message-router-sites-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        sites.json: |
          {
            "mimis-kreativstudio": {
              "recipient": "{{ .mimis_recipient_email }}",
              "subject": "Neue Anfrage für Mimi's Kreativstudio",
              "allowed_origins": ["https://mimis-kreativstudio.de", "https://www.mimis-kreativstudio.de"]
            },
            "business-website": {
              "recipient": "{{ .business_recipient_email }}",
              "subject": "Neue Anfrage über die Website",
              "allowed_origins": ["https://jakob-lingel.dev", "https://www.jakob-lingel.dev", "http://localhost:3000", "http://localhost:4321"]
            },
            "joy-alemazung": {
              "recipient": "{{ .joy_alemazung_recipient_email }}",
              "subject": "Neue Nachricht über alemazung.com",
              "allowed_origins": ["https://alemazung.com", "https://www.alemazung.com", "http://localhost:3000"]
            }
          }
  data:
    - secretKey: mimis_recipient_email
      remoteRef:
        key: /mimis-kreativstudio/notifications/recipient_email_address
    - secretKey: business_recipient_email
      remoteRef:
        key: /business-website/notifications/recipient_email_address
    - secretKey: joy_alemazung_recipient_email
      remoteRef:
        key: /joy_alemazung/notifications/recipient_email_address
