apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: message-router-external-secret
  namespace: message-router
spec:
  refreshInterval: 6h

  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore

  target:
    name: message-router-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        RESEND_API_KEY: "{{ .resend_api_key }}"
        API_KEY: "{{ .api_key }}"
        FROM_EMAIL: "{{ .from_email }}"

  data:
    - secretKey: resend_api_key
      remoteRef:
        key: /message-router/resend-api-key
    - secretKey: api_key
      remoteRef:
        key: /message-router/api-key
    - secretKey: from_email
      remoteRef:
        key: /message-router/from-email
