apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mimis-kreativstudio-external-secret
  namespace: message-router
spec:
  refreshInterval: 6h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: mimis-kreativstudio-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        sites.json: |
          {
            "mimis-kreativstudio": {
              "recipient": "{{ .recipient_email }}",
              "subject": "Neue Anfrage für Mimi's Kreativstudio",
              "allowed_origins": ["https://mimis-kreativstudio.de", "https://www.mimis-kreativstudio.de"]
            }
          }
  data:
    - secretKey: recipient_email
      remoteRef:
        key: /mimis-kreativstudio/notifications/recipient_email_address
