apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-cookie-secret-external-secret
  namespace: oauth2-proxy
spec:
  refreshInterval: 6h

  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore

  target:
    name: oauth2-proxy-cookie-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        cookie-secret: "{{ .cookie_secret }}"

  data:
    - secretKey: cookie_secret
      remoteRef:
        key: /oauth2-proxy/cookie-secret
