apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: schluesselmomente-be-external-secret
  namespace: schluesselmomente
spec:
  refreshInterval: 12h

  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore

  target:
    name: schluesselmomente-be-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        MAILGUN_API_KEY: "{{ .mailgun_api_key }}"
        MAIL: "{{ .mail }}"

  data:
    - secretKey: mailgun_api_key
      remoteRef:
        key: /schluesselmomente/be/mailgun_api_key
    - secretKey: mail
      remoteRef:
        key: /schluesselmomente/be/mail
