apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: schluesselmomente-be-external-secret
  namespace: schluesselmomente
spec:
  refreshInterval: 12h

  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore

  target:
    name: schluesselmomente-be-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        MAILGUN_API_KEY: "{{ .mailgun_api_key }}"
        SCHLUESSELMOMENTE_SENDKEY: "{{ .schluesselmomente_sendkey }}"
        MAIL: "{{ .mail }}"
        PASSWORD: "{{ .password }}"
        HOST: "smtp.zoho.eu"
        PORT: "465"


  data:
    - secretKey: mailgun_api_key
      remoteRef:
        key: /schluesselmomente/be/mailgun_api_key
    - secretKey: schluesselmomente_sendkey
      remoteRef:
        key: /schluesselmomente/be/schluesselmomente_sendkey
    - secretKey: mail
      remoteRef:
        key: /schluesselmomente/be/mail
    - secretKey: password
      remoteRef:
        key: /schluesselmomente/be/password
