apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: teachme-keycloak-db-external-secret
  namespace: teachme
spec:
  refreshInterval: 6h

  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore

  target:
    name: teachme-keycloak-db-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # PostgreSQL credentials (must match keycloak secret KC_DB_USERNAME/KC_DB_PASSWORD)
        POSTGRES_DB: "keycloak"
        POSTGRES_USER: "{{ .postgres_user }}"
        POSTGRES_PASSWORD: "{{ .postgres_password }}"

  data:
    - secretKey: postgres_user
      remoteRef:
        key: /teachme/keycloak-db/postgres_user
    - secretKey: postgres_password
      remoteRef:
        key: /teachme/keycloak-db/postgres_password
