apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: teachme-backend-external-secret
  namespace: teachme
spec:
  refreshInterval: 6h

  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore

  target:
    name: teachme-backend-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # Database credentials
        DB_PASSWORD: "{{ .db_password }}"
        DB_USERNAME: "{{ .db_username }}"
        DB_HOST: "teachme-backend-db-service"
        DB_PORT: "5432"
        DB_DATABASE: "teachme_db"

        # JWT Secrets
        JWT_SECRET: "{{ .jwt_secret }}"
        JWT_REFRESH_SECRET: "{{ .jwt_refresh_secret }}"
        SESSION_SECRET: "{{ .session_secret }}"

        # Stripe
        STRIPE_TEST: "{{ .stripe_test_key }}"
        STRIPE_WEBHOOK_SECRET: "{{ .stripe_webhook_secret }}"

        # Recaptcha
        RECAPTCHA_SHARED_SECRET: "{{ .recaptcha_secret }}"

        # Google Cloud
        GCLOUD_API_KEY: "{{ .gcloud_api_key }}"

        # Keycloak
        KEYCLOAK_REALM_URL: "https://auth.teachly.store/realms/teachly"
        KEYCLOAK_CLIENT_SECRET: "{{ .keycloak_client_secret }}"

  data:
    - secretKey: db_password
      remoteRef:
        key: /teachme/backend/db_password
    - secretKey: db_username
      remoteRef:
        key: /teachme/backend/db_username
    - secretKey: jwt_secret
      remoteRef:
        key: /teachme/backend/jwt_secret
    - secretKey: jwt_refresh_secret
      remoteRef:
        key: /teachme/backend/jwt_refresh_secret
    - secretKey: session_secret
      remoteRef:
        key: /teachme/backend/session_secret
    - secretKey: stripe_test_key
      remoteRef:
        key: /teachme/backend/stripe_test_key
    - secretKey: stripe_webhook_secret
      remoteRef:
        key: /teachme/backend/stripe_webhook_secret
    - secretKey: recaptcha_secret
      remoteRef:
        key: /teachme/backend/recaptcha_secret
    - secretKey: gcloud_api_key
      remoteRef:
        key: /teachme/backend/gcloud_api_key
    - secretKey: keycloak_client_secret
      remoteRef:
        key: /teachme/backend/keycloak_client_secret
