apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless-web
  namespace: paperless-ngx
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paperless-web
  template:
    metadata:
      labels:
        app: paperless-web
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "2"
      nodeSelector:
        node-type: homelab
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "homelab"
          effect: "NoSchedule"
      containers:
        - name: web
          image: ghcr.io/paperless-ngx/paperless-ngx:latest
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: PAPERLESS_REDIS
              value: "redis://10.43.43.160:6379"
            - name: PAPERLESS_DBHOST
              value: "10.43.255.222"
            - name: PAPERLESS_DBNAME
              value: "paperless"
            - name: PAPERLESS_DBUSER
              value: "paperless"
            - name: PAPERLESS_DBPASSWORD
              valueFrom:
                secretKeyRef:
                  name: paperless-secret
                  key: PAPERLESS_DB_PASSWORD
            - name: PAPERLESS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: paperless-secret
                  key: PAPERLESS_SECRET_KEY
            - name: PAPERLESS_TIKA_ENABLED
              value: "1"
            - name: PAPERLESS_TIKA_GOTENBERG_ENDPOINT
              value: "http://10.43.1.236:3000"
            - name: PAPERLESS_TIKA_ENDPOINT
              value: "http://10.43.194.215:9998"
            - name: PAPERLESS_TIME_ZONE
              value: "Europe/Berlin"
            - name: PAPERLESS_URL
              value: "https://paperless.jakob-lingel.dev"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          volumeMounts:
            - name: paperless-data
              mountPath: /usr/src/paperless/media
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
      volumes:
        - name: paperless-data
          persistentVolumeClaim:
            claimName: paperless-data
