apiVersion: v1
kind: Service
metadata:
  name: paperless-postgres
  namespace: paperless-ngx
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: paperless-postgres
