apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: schluesselmomente-be
  name: schluesselmomente-be
  namespace: schluesselmomente
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schluesselmomente-be
  template:
    metadata:
      annotations:
      labels:
        app: schluesselmomente-be
    spec:
      containers:
        - image: ghcr.io/davidcode2/schluesselmomente-be:latest
          name: schluesselmomente-be
          envFrom:
            - secretRef:
                name: schluesselmomente-be-secret
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          ports:
            - containerPort: 99
          readinessProbe:
            httpGet:
              path: /
              port: 99
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
      restartPolicy: Always
