apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: schluesselmomente-fe
    app: schluesselmomente-fe
  name: schluesselmomente-fe
  namespace: schluesselmomente
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: schluesselmomente-fe
      app: schluesselmomente-fe
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.37.0 (HEAD)
      labels:
        io.kompose.service: schluesselmomente-fe
        app: schluesselmomente-fe
    spec:
      containers:
        - image: ghcr.io/davidcode2/schluesselmomente:1.0.3
          name: schluesselmomente
      restartPolicy: Always
