apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: strapi-ingress
  namespace: joy-alemazung
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  rules:
    # --- Debugging / Testing Hosts ---
    - host: "api.alemazung.immoly.io"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: strapi-app-service
                port:
                  number: 1337
    - host: "www.api.alemazung.immoly.io"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: strapi-app-service
                port:
                  number: 1337
    # --- Production Hosts (.de) ---
    - host: "api.alemazung.de"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: strapi-app-service
                port:
                  number: 1337
    - host: "www.api.alemazung.de"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: strapi-app-service
                port:
                  number: 1337
  tls:
  - hosts:
      - "api.alemazung.immoly.io"
      - "www.api.alemazung.immoly.io"
      #- "api.alemazung.de"
      #- "www.api.alemazung.de"
    secretName: alemazung-cms-tls
