apiVersion: v1
kind: Secret
metadata:
  name: strapi-secrets
type: Opaque
stringData:
  .env: |
    DATABASE_HOST=your-database-host
    DATABASE_PORT=5432
    DATABASE_NAME=strapi
    DATABASE_USERNAME=strapi
    DATABASE_PASSWORD=your-secure-password
    JWT_SECRET=your-jwt-secret-key
    ADMIN_JWT_SECRET=your-admin-jwt-secret
    API_TOKEN_SALT=your-api-token-salt

    DATABASE_CLIENT: ${DATABASE_CLIENT}
    DATABASE_HOST: strapiDB
    DATABASE_PORT: ${DATABASE_PORT}
    DATABASE_NAME: ${DATABASE_NAME}
    DATABASE_USERNAME: ${DATABASE_USERNAME}
    DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    JWT_SECRET: ${JWT_SECRET}
    ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
    APP_KEYS: ${APP_KEYS}
    NODE_ENV: ${NODE_ENV}


    # Server
HOST=0.0.0.0
PORT=1337

# Secrets
APP_KEYS=UENwJg+ss6CzA4CJpCmReQ==,cLprq+45h2107UOQnj5OMg==,nD1nTLIkIhiNc1HuLP4lnA==,FI3I48dPdTX7GAKAc1dnPQ==
API_TOKEN_SALT=jQ3ebYTeXtmTqe7R310tew==
ADMIN_JWT_SECRET=fIJP6O+y1QRoBt917N1/2Q==
TRANSFER_TOKEN_SALT=XkXYvSKWshB/DsuKBmWd6w==
ENCRYPTION_KEY=qZboUURC5SQul4IRrY8D4A==

# Database
DATABASE_CLIENT=postgres
DATABASE_HOST=127.0.0.1
DATABASE_PORT=5432
DATABASE_NAME=strapi
DATABASE_USERNAME=strapi_user
DATABASE_PASSWORD=pHyn@CpX*X5*oYc!J8LsJusoU
DATABASE_SSL=false
DATABASE_FILENAME=
JWT_SECRET=9Z+zIhYrk5HKnHJA5xN/yw==

NODE_ENV=production

