apiVersion: v1
kind: Service
metadata:
  name: gmymf-storefront
  namespace: gmymf-storefront
spec:
  type: ClusterIP
  selector:
    app: gmymf-storefront
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
