apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-at-sea-strapi-uploads-pvc
  namespace: home-at-sea
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
