apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: schreinerei-db-external-secret
  namespace: schreinerei
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 6h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: schreinerei-db-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        DATABASE_URL: "postgresql://{{ .db_user }}:{{ .db_password }}@schreinerei-postgres-service:5432/{{ .db_name }}"
        POSTGRES_DB: "{{ .db_name }}"
        POSTGRES_USER: "{{ .db_user }}"
        POSTGRES_PASSWORD: "{{ .db_password }}"
        KEYCLOAK_ADMIN_CLIENT_ID: "{{ .keycloak_admin_client_id }}"
        KEYCLOAK_ADMIN_CLIENT_SECRET: "{{ .keycloak_admin_client_secret }}"
        KEYCLOAK_ADMIN_REALM: "{{ .keycloak_admin_realm }}"
        MOLLIE_API_KEY: "{{ .mollie_api_key }}"
  data:
    - secretKey: db_user
      remoteRef:
        key: /schreinerei/db/user
    - secretKey: db_password
      remoteRef:
        key: /schreinerei/db/password
    - secretKey: db_name
      remoteRef:
        key: /schreinerei/db/name
    - secretKey: keycloak_admin_client_id
      remoteRef:
        key: /schreinerei/keycloak/admin_client_id
    - secretKey: keycloak_admin_client_secret
      remoteRef:
        key: /schreinerei/keycloak/admin_client_secret
    - secretKey: keycloak_admin_realm
      remoteRef:
        key: /schreinerei/keycloak/admin_realm
    - secretKey: mollie_api_key
      remoteRef:
        key: /schreinerei/mollie/api_key
