apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: schreinerei-db-external-secret
  namespace: schreinerei
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 6h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: schreinerei-db-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        DATABASE_URL: "postgresql://{{ .db_user }}:{{ .db_password }}@schreinerei-postgres-service:5432/{{ .db_name }}"
        POSTGRES_DB: "{{ .db_name }}"
        POSTGRES_USER: "{{ .db_user }}"
        POSTGRES_PASSWORD: "{{ .db_password }}"
  data:
    - secretKey: db_user
      remoteRef:
        key: /schreinerei/db/user
    - secretKey: db_password
      remoteRef:
        key: /schreinerei/db/password
    - secretKey: db_name
      remoteRef:
        key: /schreinerei/db/name
