apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
  name: strapi-data
  namespace: schluesselmomente-cms
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
