apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
  name: strapi-uploads-pvc
  namespace: schluesselmomente-cms
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
