apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: smiles-message-router-secret
  namespace: smiles
spec:
  refreshInterval: 6h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: smiles-message-router-secret
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: message-router-api-key
      remoteRef:
        key: /message-router/api-key
