apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: alemazung-app
    app: alemazung-app
  name: alemazung-app
  namespace: joy-alemazung
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: alemazung-app
      app: alemazung-app
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.37.0 (HEAD)
      labels:
        io.kompose.service: alemazung-app
        app: alemazung-app
    spec:
      containers:
        - image: ghcr.io/davidcode2/dr-joy-alemazung:0.13.22
          name: alemazung-app
          envFrom:
            - secretRef:
                name: alemazung-strapi-secret
      restartPolicy: Always
