apiVersion: v1
kind: Secret
metadata:
  name: alemazung-strapi-secret
  namespace: joy-alemazung
type: Opaque
data:
  # base64 encoded
  NEXT_PUBLIC_STRAPI_API_TOKEN_PROD: MDI5YTg4MmUwYWExNGQ2MTgyZTUyOWY3NjE0NzYzNDFiYTA1MDIzNDg1MDg2MzUxODE1YjA5ZDdjNjk5NTY2NmQ4MjcwYTJjN2Q1Y2ZiMGJiNTA5MzM2ZmQ0OGQ5NDNiYzVmYTVlZjY5NzJmYmIyYzMyNDYxOGY3NmUwNGJlZjBiZTRmMDk4ZjcxNDc0YTE3YThiZmQ4N2JlZmMxNWU2MTZjNGUwNDExNDc0NzY0Yjc2MjM2YzNhZDk0MmE0NDFkYmNmMGRjNTg0YTAxMDkzMzE5YjBlOTkzZDYzZmJiYTdiYmMyMzAyMWM4MDlmNzFlZjE0NWY4YmU0NjcxNGVmNw==
  NEXT_PUBLIC_PAGE_LIMIT: Ng==
  NEXT_PUBLIC_STRAPI_API_URL_PROD: aHR0cHM6Ly9hcGkuYWxlbWF6dW5nLmltbW9seS5pbw==
  STRAPI_API_URL_PROD: aHR0cHM6Ly9hcGkuYWxlbWF6dW5nLmltbW9seS5pbw==
  STRAPI_API_TOKEN_PROD: MDI5YTg4MmUwYWExNGQ2MTgyZTUyOWY3NjE0NzYzNDFiYTA1MDIzNDg1MDg2MzUxODE1YjA5ZDdjNjk5NTY2NmQ4MjcwYTJjN2Q1Y2ZiMGJiNTA5MzM2ZmQ0OGQ5NDNiYzVmYTVlZjY5NzJmYmIyYzMyNDYxOGY3NmUwNGJlZjBiZTRmMDk4ZjcxNDc0YTE3YThiZmQ4N2JlZmMxNWU2MTZjNGUwNDExNDc0NzY0Yjc2MjM2YzNhZDk0MmE0NDFkYmNmMGRjNTg0YTAxMDkzMzE5YjBlOTkzZDYzZmJiYTdiYmMyMzAyMWM4MDlmNzFlZjE0NWY4YmU0NjcxNGVmNw==

